Repository alibaba/BladeDISC, pull requests merged in 2021-12, with the labels that each got.

#13 [#to 38272797] rename quickstart_tensorflow.md
  docs/quickstart_tensorflow.md
Labels: documentation

#15 using official docker org
  scripts/ci/deploy_docker.sh
Labels: CI

#19 Update deploy job branch ref
  .github/workflows/main.yml
Labels: CI

#10 [DOC] add runtime abstraction layer doc
  docs/developers/RAL.png
  docs/developers/runtime_abstraction_layer.md
Labels: documentation

#22 Support shuffle for data type smaller than 32-bit (e.g., fp16)
  tao_compiler/mlir/disc/tests/tensorflow_ops/data/sum_row_s_2d_f16.mlir
  tao_compiler/mlir/disc/tests/tensorflow_ops/data/sum_row_s_3d_f16.mlir
  tao_compiler/mlir/disc/tests/tensorflow_ops/sum.cc
  tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc
Labels: enhancement

#17 Add a draft version of README.md
  README_.md
  docs/dingtalk_support.png
  docs/numbers.png
  docs/quickstart_tensorflow.md
Labels: documentation

#24 [Torch] add bert tutorial
  examples/pytorch/inference/torch_bert_tutorial.md
Labels: documentation

#12 Add pass_pipeline.md
  docs/developers/pass_pipeline.md
Labels: documentation

#31 [Torch] change tutorial path
  docs/tutorials/torch_bert_inference.md
Labels: documentation

#20 install BladeDISC with Docker
  .github/workflows/main.yml
  docs/install_with_docker.md
  scripts/ci/deploy_tf_wrapper.sh
Labels: documentation

#29 [Torch] Add README
  pytorch_blade/README.md
Labels: documentation

#33 Examples and tutorials for TensorFlow optimization.
  docs/tutorials/tensorflow_inference_and_training.md
  docs/tutorials/torch_bert_inference.md
  examples/TensorFlow/Inference/BERT/README.md
  examples/TensorFlow/Inference/BERT/download_model.sh
  examples/TensorFlow/Inference/BERT/main.py
  examples/TensorFlow/Train/DeePMD/README.md
  examples/TensorFlow/Train/DeePMD/download_data.sh
  examples/TensorFlow/Train/DeePMD/main.py
  examples/TensorFlow/Train/DeePMD/run.sh
Labels: documentation, good first issue

#35 add contribution documentation
  docs/contribution.md
Labels: documentation

#38 [Torch] rename modules with nouns
  docs/tutorials/torch_bert_inference.md
  pytorch_blade/tests/__init__.py
  pytorch_blade/tests/mlir/testing_utils.py
  pytorch_blade/tests/test_export.py
  pytorch_blade/tests/test_passes.py
  pytorch_blade/torch_blade/__init__.py
  pytorch_blade/torch_blade/clustering/__init__.py
  pytorch_blade/torch_blade/exporter.py
  pytorch_blade/torch_blade/optimization.py
  pytorch_blade/torch_blade/testing/__init__.py
  pytorch_blade/torch_blade/tools/shape_inference.py
Labels: enhancement

#40 add quick start for PyTorch users
  README_.md
  docs/quickstart.md
  docs/quickstart_tensorflow.md
Labels: documentation
