Repository alibaba/BladeDISC, pull requests merged in 2022-03, with the labels that each got.

#130 Speculation strategy with better TLP for row-reduce.
  tao_compiler/mlir/disc/transforms/codegen_utils.h
  tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc
Labels: enhancement

#128 UT for corner case of PTXAS error before v11.1.
  tao_compiler/mlir/disc/tests/regression/corner_case.cc
  tao_compiler/mlir/disc/tests/regression/data/corner_case_error_before_ptxas11100.mlir
Labels: bug

#147 Add shape constraint for mhlo::DotOp.
  tao_compiler/mlir/disc/transforms/shape_utils.cc
Labels: enhancement

#168 Torch converter for several ops.
  pytorch_blade/src/compiler/jit/BUILD
  pytorch_blade/src/compiler/mlir/converters/impl/element_wise_binary.cpp
  pytorch_blade/src/compiler/mlir/converters/impl/element_wise_unary.cpp
  pytorch_blade/src/compiler/mlir/converters/impl/matmul.cpp
  pytorch_blade/src/compiler/mlir/converters/impl/shapes.cpp
  pytorch_blade/src/compiler/mlir/converters/impl/tensor.cpp
  pytorch_blade/src/compiler/mlir/converters/mlir_type_utils.cpp
  pytorch_blade/tests/mlir/test_disc_binary_ops.py
  pytorch_blade/tests/mlir/test_disc_matmul.py
  pytorch_blade/tests/mlir/test_disc_shapes.py
Labels: enhancement

#171 [Tensorflow]add c++ source code for tensorflow blade
  scripts/ci/test_tensorflow_blade.sh
  tensorflow_blade/.bazelrc
  tensorflow_blade/.flake8
  tensorflow_blade/.isort.cfg
  tensorflow_blade/.mypy.ini
  tensorflow_blade/BUILD
  tensorflow_blade/build.py
  tensorflow_blade/build_defs.bzl
  tensorflow_blade/src/BUILD
  tensorflow_blade/src/custom_ops/BUILD
  tensorflow_blade/src/custom_ops/build_defs.bzl
  tensorflow_blade/src/custom_ops/non_max_suppression/BUILD
  tensorflow_blade/src/custom_ops/non_max_suppression/cuda_common.cu.h
  tensorflow_blade/src/custom_ops/non_max_suppression/gpu_non_max_suppression.cu.h
  tensorflow_blade/src/custom_ops/non_max_suppression/gpu_non_max_suppression_op.cu.cc
  tensorflow_blade/src/custom_ops/rnn_ops/BUILD
  tensorflow_blade/src/custom_ops/rnn_ops/fused_lstm_element_wise_op.cc
  tensorflow_blade/src/custom_ops/rnn_ops/fused_lstm_element_wise_op_gpu.cu.cc
  tensorflow_blade/src/custom_ops/rnn_ops/fused_lstm_element_wise_op_kernels.cu.h
  tensorflow_blade/src/custom_ops/rnn_ops/rnn_ops.cc
  tensorflow_blade/src/custom_ops/trt_engine_op/BUILD
  tensorflow_blade/src/custom_ops/trt_engine_op/trt_engine_op.cc
  tensorflow_blade/src/pybind.cpp
  tensorflow_blade/src/tensorrt/BUILD
  tensorflow_blade/src/tensorrt/bridge/macros.h
  tensorflow_blade/src/tensorrt/bridge/tensorrt_common.cpp
  tensorflow_blade/src/tensorrt/bridge/tensorrt_common.h
  tensorflow_blade/src/tensorrt/bridge/tensorrt_flags.cpp
  tensorflow_blade/src/tensorrt/bridge/tensorrt_flags.h
  tensorflow_blade/src/tensorrt/bridge/tensorrt_logger.cpp
  tensorflow_blade/src/tensorrt/bridge/tensorrt_logger.h
  tensorflow_blade/src/tensorrt/bridge/tensorrt_onnx_parser.cpp
  tensorflow_blade/src/tensorrt/bridge/tensorrt_onnx_parser.h
  tensorflow_blade/src/tensorrt/bridge/tensorrt_tf_allocator.cc
  tensorflow_blade/src/tensorrt/bridge/tensorrt_tf_allocator.h
  tensorflow_blade/src/tensorrt/bridge/tensorrt_tf_resource_mgr.cc
  tensorflow_blade/src/tensorrt/bridge/tensorrt_tf_resource_mgr.h
  tensorflow_blade/src/tensorrt/pybind_functions.cpp
  tensorflow_blade/src/tensorrt/pybind_functions.h
  tensorflow_blade/src/tf_blade.lds
  tensorflow_blade/src/util/BUILD
  tensorflow_blade/src/util/logging.h
  tensorflow_blade/src/util/tf_allocator_util.cc
  tensorflow_blade/src/util/tf_allocator_util.h
  tensorflow_blade/tests/BUILD
  tensorflow_blade/tests/__init__.py
  tensorflow_blade/tests/build_defs.bzl
  tensorflow_blade/tests/custom_ops/BUILD
  tensorflow_blade/tests/custom_ops/__init__.py
  tensorflow_blade/tests/custom_ops/non_max_suppression/BUILD
  tensorflow_blade/tests/custom_ops/non_max_suppression/__init__.py
  tensorflow_blade/tests/custom_ops/non_max_suppression/non_max_suppression_op_test.py
  tensorflow_blade/tests/custom_ops/rnn_ops/BUILD
  tensorflow_blade/tests/custom_ops/rnn_ops/__init__.py
  tensorflow_blade/tests/custom_ops/rnn_ops/fused_lstm_element_wise_op_test.py
  tensorflow_blade/tests/custom_ops/tf_blade_ops_ut_common.py
  third_party/bazel/blade_helper/blade_helper_configure.bzl
  third_party/bazel/blade_helper/build_defs.bzl.tpl
  third_party/bazel/common.bzl
Labels: TensorflowBlade

#192 GPU Conv1D support.
  pytorch_blade/src/compiler/mlir/converters/impl/convolution.cpp
  pytorch_blade/tests/mlir/test_disc_conv_ops.py
  tao_compiler/mlir/disc/transforms/disc_lower_to_library_call.cc
  tao_compiler/mlir/disc/transforms/gpu_conv_padding.cc
  tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc
Labels: enhancement

#179 DimValue mapping for reshape, broadcast and slice.
  tao_compiler/mlir/disc/transforms/shape_utils.cc
  tao_compiler/mlir/disc/transforms/shape_utils.h
Labels: enhancement

#167 Dot batching optimization.
  tao_compiler/mlir/disc/BUILD
  tao_compiler/mlir/disc/disc_compiler.cc
  tao_compiler/mlir/disc/transforms/PassDetail.h
  tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
  tao_compiler/mlir/disc/transforms/disc_passes.td
  tao_compiler/mlir/disc/transforms/passes.h
  tao_compiler/mlir/disc/transforms/shape_utils.cc
  tao_compiler/mlir/disc/transforms/shape_utils.h
  tao_compiler/mlir/disc/transforms/tests/disc-dot-merge.mlir
Labels: enhancement

#198 [Tensorflow][docs][to #195]tensorflow blade tutorials
  scripts/ci/test_tensorflow_blade.sh
  tensorflow_blade/README.md
  tensorflow_blade/build.py
  tensorflow_blade/docs/build_from_source.md
  tensorflow_blade/docs/tutorials/tensorflow_blade_bert_inference.md
  tensorflow_blade/examples/Inference/CUDA/BERT/README.md
  tensorflow_blade/examples/Inference/CUDA/BERT/bert_inference_opt.py
  tensorflow_blade/setup.py
  tensorflow_blade/src/BUILD
  tensorflow_blade/src/custom_ops/non_max_suppression/BUILD
  tensorflow_blade/src/custom_ops/non_max_suppression/cuda_common.cu.h
  tensorflow_blade/src/custom_ops/non_max_suppression/gpu_non_max_suppression.cu.h
  tensorflow_blade/src/custom_ops/non_max_suppression/gpu_non_max_suppression_op.cu.cc
  tensorflow_blade/src/custom_ops/rnn_ops/BUILD
  tensorflow_blade/src/custom_ops/rnn_ops/fused_lstm_element_wise_op.cc
  tensorflow_blade/src/custom_ops/rnn_ops/fused_lstm_element_wise_op_gpu.cu.cc
  tensorflow_blade/src/custom_ops/rnn_ops/fused_lstm_element_wise_op_kernels.cu.h
  tensorflow_blade/src/custom_ops/rnn_ops/rnn_ops.cc
  tensorflow_blade/tests/custom_ops/BUILD
  tensorflow_blade/tests/custom_ops/non_max_suppression/BUILD
  tensorflow_blade/tests/custom_ops/non_max_suppression/__init__.py
  tensorflow_blade/tests/custom_ops/non_max_suppression/non_max_suppression_op_test.py
  tensorflow_blade/tests/custom_ops/rnn_ops/BUILD
  tensorflow_blade/tests/custom_ops/rnn_ops/__init__.py
  tensorflow_blade/tests/custom_ops/rnn_ops/fused_lstm_element_wise_op_test.py
  tensorflow_blade/tests/custom_ops/tf_blade_ops_ut_common.py
  tensorflow_blade/tests/gpu/BUILD
  tensorflow_blade/tests/gpu/tf_lstm_element_wise_ops_test.py
  tensorflow_blade/tests/gpu/tf_non_max_suppression_opt_test.py
  tensorflow_blade/tests/util/BUILD
  tensorflow_blade/tests/util/tf_hierarchy_pattern_match_test.py
  tensorflow_blade/tf_blade/gpu/BUILD
  tensorflow_blade/tf_blade/gpu/tf_lstm_element_wise_ops.py
  tensorflow_blade/tf_blade/gpu/tf_non_max_suppression_opt.py
  tensorflow_blade/tf_blade/gpu/tf_to_trt.py
  tensorflow_blade/tf_blade/util/BUILD
  tensorflow_blade/tf_blade/util/tf2onnx_import_helper.py
Labels: documentation, TensorflowBlade

#204 adapt for internal blade build
  tensorflow_blade/build.py
  third_party/bazel/blade_helper/blade_helper_configure.bzl
  third_party/bazel/blade_helper/build_defs.bzl.tpl
  third_party/bazel/cuda_static/BUILD
  third_party/bazel/cuda_static/build_defs.bzl.tpl
  third_party/bazel/cuda_static/cuda_static.BUILD.tpl
  third_party/bazel/cuda_static/cuda_static_configure.bzl
  third_party/bazel/tf/build_defs.bzl.tpl
  third_party/bazel/tf/tf_configure.bzl
Labels: CI

#203 DotOp merge optimization.
  tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
  tao_compiler/mlir/disc/transforms/tests/disc-dot-merge.mlir
Labels: enhancement
