Repository alibaba/BladeDISC, pull requests merged in 2022-06, with the labels that each got.

#348 Add environment setting to enable CUDA fast math on NVIDIA GPU.
  tao_compiler/mlir/disc/tests/tensorflow_ops/floor_div.cc
  tao_compiler/mlir/disc/transforms/disc_gpu_kernel_to_blob.cc
Labels: feature

#349 Arch-aware schedule selection enhancement for GPU fusion.
  tao_compiler/mlir/disc/disc_compiler.cc
  tao_compiler/mlir/disc/disc_compiler.h
  tao_compiler/mlir/disc/disc_compiler_main.cc
  tao_compiler/mlir/disc/tests/regression/data/layer_norm.mlir
  tao_compiler/mlir/disc/tests/regression/data/softmax.mlir
  tao_compiler/mlir/disc/transforms/codegen_utils.cc
  tao_compiler/mlir/disc/transforms/codegen_utils.h
  tao_compiler/mlir/disc/transforms/disc_gpu_kernel_to_blob.cc
  tao_compiler/mlir/disc/transforms/disc_passes.td
  tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc
  tao_compiler/mlir/disc/transforms/passes.h
  tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-legalize-roots-to-loops.mlir
  tao_compiler/mlir/disc/transforms/tests/specialize_fusion_with_speculation.mlir
Labels: enhancement

#351 Loop unroll and instruction interleave for GPU codegen.
  tao_compiler/mlir/disc/BUILD
  tao_compiler/mlir/disc/disc_compiler.cc
  tao_compiler/mlir/disc/transforms/codegen_utils.cc
  tao_compiler/mlir/disc/transforms/codegen_utils.h
  tao_compiler/mlir/disc/transforms/disc_for_loop_unroll_interleave.cc
  tao_compiler/mlir/disc/transforms/disc_passes.td
  tao_compiler/mlir/disc/transforms/passes.h
  tao_compiler/mlir/disc/transforms/tests/unroll-interleave.mlir
Labels: enhancement, feature

#350 Row-reduce ops interleave for kStitch codegen.
  tao_compiler/mlir/disc/BUILD
  tao_compiler/mlir/disc/disc_util.cc
  tao_compiler/mlir/disc/disc_util.h
  tao_compiler/mlir/disc/tests/mlir_feature_test.cc
  tao_compiler/mlir/disc/transforms/disc_dot_merge.cc
  tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc
  tao_compiler/mlir/disc/transforms/fusion_utils.cc
  tao_compiler/mlir/disc/transforms/fusion_utils.h
  tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.cc
  tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.h
  tao_compiler/mlir/disc/transforms/lhlo_elemental_utils.h
  tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc
  tao_compiler/mlir/disc/transforms/parallel_loop_collapsing.cc
  tao_compiler/mlir/disc/transforms/parallel_loop_tiling.cc
  tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-legalize-roots-to-loops.mlir
Labels: enhancement

#380 GPU kLoop fusion fully vectorization optimization.
  tao_compiler/mlir/disc/transforms/codegen_utils.cc
  tao_compiler/mlir/disc/transforms/codegen_utils.h
  tao_compiler/mlir/disc/transforms/disc_for_loop_unroll_interleave.cc
  tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc
  tao_compiler/mlir/disc/transforms/fusion_utils.cc
  tao_compiler/mlir/disc/transforms/fusion_utils.h
  tao_compiler/mlir/disc/transforms/lhlo_elemental_utils.cc
  tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc
  tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-legalize-roots-to-loops.mlir
  tao_compiler/mlir/disc/transforms/tests/gpu-only-unroll-interleave.mlir
Labels: enhancement

#427 propagates more shape constraint attributes
  tao_compiler/mlir/disc/transforms/disc_shape_optimization.cc
  tao_compiler/mlir/disc/transforms/tests/disc-shape-optimization.mlir
Labels: Shape Constraint IR
